### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [c-neto/ansible-configure-fedora#1]
I have a question about your ansible config, i want to know the reason of the selinux disabling key and not using the key to withelist the software who block instead.

True question not a troll.

**Comment by c-neto** [comment]
Not have specific motivation. I disable because impact Docker volumes and Docker network. 

Your question is valid. This ansible playbook need some updates.

**Comment by ghost** [comment]
> Not have specific motivation. I disable because impact Docker volumes and Docker network.
> 
> Your question is valid. This ansible playbook need some updates.

thanks was curious since i write my own ansible based one and i checked on git other to see if i had forgotten something
